name: Deploy

on:
  release:
    types: [ released ]

jobs:
  build:
    name: Deploy
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 90

    steps:
      - name: Update to packagist
        id: packagist-update
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}' -d'{"repository":{"url":"${{ secrets.PACKAGIST_PACKAGE_URL }}"}}'