name: Run Tests

on: push

jobs:
  code-tests:
    runs-on: [ubuntu-latest]
    timeout-minutes: 90

    steps:
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute Easy Code Style test
        run: composer check-cs

      - name: Execute PHPStan
        run: composer phpstan